### ISSUE TITLE
Checking images added with before/after pseudoelement

### ISSUE THREAD

**Issue by pkubiak** [pkubiak/logo_extractor#2]
Using CSS before/after pseudo element it is possible to insert image like this:

```CSS
#logo:before { content: url(/path/to/image.jpg); }
```

We should try to handle this case!
